- name: Ensure .ssh directory exists.
  become: true
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized key took from file
  become: true
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
  tags:
    - dotfiles
    - install
    - ssh

- name: set ownership
  become: true
  file:
    owner: "{{ user }}"
    group: "{{ user }}"
    path: "{{ item }}"
  loop:
    - "/home/{{ user }}/.ssh/id_rsa"
    - "/home/{{ user }}/.ssh/id_rsa.pub"
