- name: Install packages
  become: true
  apt:
    name: [
      "wireshark",
      "gimp",
      "xclip",
      "screenkey",
      "tldr",
      "ripgrep",
    ]

- name: "bat: get Latest Release from Github"
  community.general.github_release:
    user: sharkdp
    repo: bat
    action: latest_release
  register: bat_release

- name: "bat: print latest release"
  ansible.builtin.debug:
    var: bat_release

- name: "bat: check existing install"
  stat:
    path: /usr/bin/bat
  no_log: true
  register: bat_exists

- name: "bat: download binary"
  become: true
  ansible.builtin.apt:
    deb: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version}}_amd64.deb"
  when: (bat_release.tag != bat_version) or (not bat_install.stat.exists)
