- name: Check that Arkade exists
  stat:
    path: /usr/local/bin/arkade
  register: arkade_exists

- name: Download Arkade
  become: true
  when: arkade_exists.stat.exists == False
  ansible.builtin.get_url:
    url: https://dl.get-arkade.dev
    dest: /tmp/arkade.sh
  tags:
    - install
    - productivity

- name: Install Arkade
  become: true
  when: arkade_exists.stat.exists == False
  ansible.builtin.shell:
    cmd: cat /tmp/arkade.sh | sh -s -- -y
  tags:
    - install
    - productivity
