---
- name: "Get Latest Release from Github"
  community.general.github_release:
    user: cli
    repo: cli
    action: latest_release
  register: gh_release

- name: Print Latest release
  ansible.builtin.debug:
    var: gh_release

- name: Download Binary
  command: "arkade get gh"
  when: gh_release.tag != gh_cli_version
