- name: Install apt-transport-https
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

- name: Add signing key
  become: true
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker.io
      - docker-compose-plugin
      - docker-registry
    state: latest
    update_cache: true

- name: Copy daemon.json
  ansible.builtin.template:
    dest: "/etc/docker/daemon.json"
    src: "daemon.json"
  become: yes
  notify: restart_docker
