---
- name: "Get Latest Release from Github"
  community.general.github_release:
    user: derailed
    repo: k9s
    action: latest_release
  register: k9s_release

- name: Print Latest release
  ansible.builtin.debug:
    var: k9s_release

- name: Download Binary
  command: "arkade get k9s"
  when: k9s_release.tag != k9s_version
