---
- name: Install kubectl signing key
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  become: true
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install kubectl
  become: true
  apt:
    name: kubectl
    state: present

- name: Install Helm
  become: true
  snap:
    name: helm
    channel: classic

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.kube/conf.d"
    state: directory

- name: Copy configs
  copy:
    dest: "{{ ansible_user_dir }}/.kube/conf.d/{{ kubectl_config_item.key }}.conf"
    content: "{{ kubectl_config_item.value }}"
    mode: 0600
  no_log: true
  loop_control:
    loop_var: kubectl_config_item
  with_items: "{{ kubectl_config | default({}) | dict2items }}"

- name: Set active
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.kube/config"
    src: "{{ ansible_user_dir }}/.kube/conf.d/{{ kubectl_config_active }}.conf"
    state: link
    force: true
#  no_log: true
  when: kubectl_config[kubectl_config_active] is defined
