---
- name: Configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/i3/config"
    src: "config.j2"

# todo - name: Install i3-status-rust
# src: https://github.com/greshake/i3status-rust/blob/master/doc/dev.md

# todo local scripts
